### ISSUE TITLE
Documentation is not proper to use this one. Could you please update the document with deep explanation about how to use this module.

### ISSUE THREAD

**Issue by imakshath** [Obie-Wan/django_hadoop#1]

**Comment by Obie-Wan** [comment]
What should be clarified? Plan is simple:
a. inherit your **CustomResultParser** from **JobResultParser** (you should implement **parse_results** to do something with job result dict, postprocess, put it into the database, etc.)

b. inherit your **CustomResultParser** from **JobManager** (override _job_result_parser with your custom job result parser)

``` python
class CustomJobManager(JobManager):
    _job_result_parser = CustomResultParser # your result parser implementation
```

c. set **JOB_MANAGER_CLASS** path, like 'your_app.your_module.CustomJobManager' and other Hadoop-specific setings.
