### ISSUE TITLE
Update Job status

### ISSUE THREAD

**Issue by lilila** [Obie-Wan/django_hadoop#3]
Hi, 

My jobs never get their status from Oozie, they are either [new, running, failed or completed]. Those are the status set by runner in process_jobs. 
For instance, I get status : completed while the hub is still running on Oozie. 

What should I do to have status corresponding to Oozie status?

**Comment by Obie-Wan** [comment]
I assume you have problems with Oozie notification url. Oozie requests this url upon job status change. 
We set it to RestJobRunner.notification_url property:

``` python
    @property
    def notification_url(self):
        """Construct notification url for Hadoop.
           Return:
               notification_url(string) - full link to django_hadoop
                                          notification view.
        """
        return 'http://%s%s' % (get_host_name(),
                                JOB_VIEW_URL.replace('JOBID', '$jobId')
                               .replace('STATUS', '$status'))
```

As you see, we construct notification url from the get_host_name and UpdateJobStateView. 
**Site.objects.get_current().domain** is returned from get_host_name().
So, you should try to do this:
- add a Site in django admin with ip/domain reachable from the host running Oozie
- setup SITE_ID in your project settings file

I've updated the docs.

**Comment by lilila** [comment]
Thank a lot. It solved the problem. 
However, I noticed that something is wrong when I run `python manage.py process_jobs` with more than one new (or failed) job. 
I suspect _exit(0) is missing in job_spawner.process_jobs : 
if not fork():
     ...
    .... 
else:
   _exit(0)

If I do not add this, children process fork new children . 
Am I doing something wrong ?

**Comment by Obie-Wan** [comment]
I forgot to call os._exit(0) in child, that's my fault.
Are you sure, that we should put os._exit(0) into parent? Common pattern is to call it from child to exit correctly (without running copied hadlers, closing descriptors, etc.). 
p.s. I understood that fork in django is anti-pattern. Celery is much more better for such cases.

**Comment by lilila** [comment]
I do not know much but I had to many oozie job launched . 
I found the solution here: http://www.petercollingridge.co.uk/blog/running-multiple-processes-python in Section: Multiple forks

**Comment by Obie-Wan** [comment]
There is a little difference.

``` python
for process in range(NUM_PROCESSES):
    pid = os.fork()
    if pid:
        children.append(pid)
    else: # !!!! CHILD CODE
        timeConsumingFunction()
        os._exit(0)
```

But condition is inverted in my code:
if **not** fork()

So, this code is also executed from child. You may add os._exit(0) to child and pull the fix.

**Comment by lilila** [comment]
Ok I will test that

**Comment by Obie-Wan** [comment]
I have checked, that's correct. FIXED

**Comment by lilila** [comment]
Great Thank you

**Comment by Obie-Wan** [comment]
I forgot that `manage.py process_jobs` is calling default JobManager instead of your custom job manager (it may skip result parsing). Please verify this.

Quick fix for `management/commands.py`:

``` python
from django_hadoop import JOB_MANAGER_CLASS
JOB_MANAGER_CLASS().process_jobs()
```
